using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EpicWAS.Models
{
    public class PickPack
    {
        
        public string Company { get; set; }
        public string MQ_SysDate { get; set; }
        public string MQ_SysTime { get; set; }
        public Int32 MQ_MtlQueueSeq { get; set; }
        public string MQ_Plant { get; set; }
        public string MQ_PartNum { get; set; }
        public decimal MQ_Quantity { get; set; }
        public string MQ_TranType { get; set; }
        public string MQ_ReferencePrefix { get; set; }
        public string MQ_Reference { get; set; }
        public string MQ_RequestedByEmpID { get; set; }
        public string MQ_SelectedByEmpID { get; set; }
        public string MQ_JobNum { get; set; }
        public Int32 MQ_AssemblySeq { get; set; }
        public string MQ_JobSeqType { get; set; }
        public Int32 MQ_JobSeq { get; set; }
        public string MQ_FromWhse { get; set; }
        public string MQ_FromBinNum { get; set; }
        public string MQ_ToWhse { get; set; }
        public string MQ_ToBinNum { get; set; }
        public Int32 MQ_NextAssemblySeq { get; set; }
        public Int32 MQ_NextJobSeq { get; set; }
        public string MQ_NeedByDate { get; set; }
        public string MQ_NeedByTime { get; set; }
        public Int32 MQ_VendorNum { get; set; }
        public string MQ_PurPoint { get; set; }
        public string MQ_PackSlip { get; set; }
        public string MQ_PackLine { get; set; }
        public Int32 MQ_OrderNum { get; set; }
        public Int32 MQ_OrderLine { get; set; }
        public Int32 MQ_OrderRelNum { get; set; }
        public string MQ_TargetJobNum { get; set; }
        public Int32 MQ_TargetAssemblySeq { get; set; }
        public Int32 MQ_TargetMtlSeq { get; set; }
        public string MQ_RevisionNum { get; set; }
        public string MQ_PartDescription { get; set; }
        public string MQ_IUM { get; set; }
        public Int32 MQ_PONum { get; set; }
        public Int32 MQ_POLine { get; set; }
        public Int32 MQ_PORelNum { get; set; }
        public bool MQ_Visible { get; set; }
        public string MQ_RMANum { get; set; }
        public Int32 MQ_RMALine { get; set; }
        public bool MQ_RMAReceipt { get; set; }
        public string MQ_RMADisp { get; set; }
        public string MQ_NCTranID { get; set; }
        public string MQ_LotNum { get; set; }
        public bool MQ_Lock { get; set; }
        public string MQ_QueueID { get; set; }
        public Int32 MQ_QueuePickSeq { get; set; }
        public Int32 MQ_ReleaseForPickingSeq { get; set; }
        public string MQ_WhseGroupCode { get; set; }
        public string MQ_TranStatus { get; set; }
        public Int32 MQ_WaveNum { get; set; }
        public string MQ_Priority { get; set; }
        public string MQ_TranSource { get; set; }
        public string MQ_LastMgrChangeEmpID { get; set; }
        public string MQ_AssignedToEmpID { get; set; }
        public string MQ_TargetTFOrdNum { get; set; }
        public Int32 MQ_TargetTFOrdLine { get; set; }
        public string MQ_PackStation { get; set; }
        public string MQ_DistributionType { get; set; }
        public string MQ_Obs10_PkgNum { get; set; }
        public string MQ_Obs10_PkgLine { get; set; }
        public string MQ_SysRevID { get; set; }
        public string MQ_SysRowID { get; set; }
        public string MQ_PCID { get; set; }
        public string MQ_EpicorFSA { get; set; }
        public string MQ_LastUsedPCID { get; set; }
        public string MQ_FromPCID { get; set; }
        public string MQ_ToPCID { get; set; }
        public string MQ_ForeignSysRowID { get; set; }
        public string MQ_UD_SysRevID { get; set; }
        public string MQ_FS_PrintStatus_c { get; set; }
        public string MQ_Updated_c { get; set; }
        public string U14_Company { get; set; }
        public string U14_Key1 { get; set; }
        public string U14_Key2 { get; set; }
        public string U14_Key3 { get; set; }
        public string U14_Key4 { get; set; }
        public string U14_Key5 { get; set; }
        public string U14_Character01 { get; set; }
        public string U14_Character02 { get; set; }
        public string U14_Character03 { get; set; }
        public string U14_Character04 { get; set; }
        public string U14_Character05 { get; set; }
        public string U14_Character06 { get; set; }
        public string U14_Character07 { get; set; }
        public string U14_Character08 { get; set; }
        public string U14_Character09 { get; set; }
        public string U14_Character10 { get; set; }
        public decimal U14_Number01 { get; set; }
        public decimal U14_Number02 { get; set; }
        public decimal U14_Number03 { get; set; }
        public decimal U14_Number04 { get; set; }
        public decimal U14_Number05 { get; set; }
        public decimal U14_Number06 { get; set; }
        public decimal U14_Number07 { get; set; }
        public decimal U14_Number08 { get; set; }
        public decimal U14_Number09 { get; set; }
        public decimal U14_Number10 { get; set; }
        public decimal U14_Number11 { get; set; }
        public decimal U14_Number12 { get; set; }
        public decimal U14_Number13 { get; set; }
        public decimal U14_Number14 { get; set; }
        public decimal U14_Number15 { get; set; }
        public decimal U14_Number16 { get; set; }
        public decimal U14_Number17 { get; set; }
        public decimal U14_Number18 { get; set; }
        public decimal U14_Number19 { get; set; }
        public decimal U14_Number20 { get; set; }
        public string U14_Date01 { get; set; }
        public string U14_Date02 { get; set; }
        public string U14_Date03 { get; set; }
        public string U14_Date04 { get; set; }
        public string U14_Date05 { get; set; }
        public string U14_Date06 { get; set; }
        public string U14_Date07 { get; set; }
        public string U14_Date08 { get; set; }
        public string U14_Date09 { get; set; }
        public string U14_Date10 { get; set; }
        public string U14_Date11 { get; set; }
        public string U14_Date12 { get; set; }
        public string U14_Date13 { get; set; }
        public string U14_Date14 { get; set; }
        public string U14_Date15 { get; set; }
        public string U14_Date16 { get; set; }
        public string U14_Date17 { get; set; }
        public string U14_Date18 { get; set; }
        public string U14_Date19 { get; set; }
        public string U14_Date20 { get; set; }
        public bool U14_CheckBox01 { get; set; }
        public bool U14_CheckBox02 { get; set; }
        public bool U14_CheckBox03 { get; set; }
        public bool U14_CheckBox04 { get; set; }
        public bool U14_CheckBox05 { get; set; }
        public bool U14_CheckBox06 { get; set; }
        public bool U14_CheckBox07 { get; set; }
        public bool U14_CheckBox08 { get; set; }
        public bool U14_CheckBox09 { get; set; }
        public bool U14_CheckBox10 { get; set; }
        public bool U14_CheckBox11 { get; set; }
        public bool U14_CheckBox12 { get; set; }
        public bool U14_CheckBox13 { get; set; }
        public bool U14_CheckBox14 { get; set; }
        public bool U14_CheckBox15 { get; set; }
        public bool U14_CheckBox16 { get; set; }
        public bool U14_CheckBox17 { get; set; }
        public bool U14_CheckBox18 { get; set; }
        public bool U14_CheckBox19 { get; set; }
        public bool U14_CheckBox20 { get; set; }


        public string U14_ShortChar01 { get; set; }
        public string U14_ShortChar02 { get; set; }
        public string U14_ShortChar03 { get; set; }
        public string U14_ShortChar04 { get; set; }
        public string U14_ShortChar05 { get; set; }
        public string U14_ShortChar06 { get; set; }
        public string U14_ShortChar07 { get; set; }
        public string U14_ShortChar08 { get; set; }
        public string U14_ShortChar09 { get; set; }
        public string U14_ShortChar10 { get; set; }
        public string U14_ShortChar11 { get; set; }
        public string U14_ShortChar12 { get; set; }
        public string U14_ShortChar13 { get; set; }
        public string U14_ShortChar14 { get; set; }
        public string U14_ShortChar15 { get; set; }
        public string U14_ShortChar16 { get; set; }
        public string U14_ShortChar17 { get; set; }
        public string U14_ShortChar18 { get; set; }
        public string U14_ShortChar19 { get; set; }
        public string U14_ShortChar20 { get; set; }

        public string U14_GlobalUD14 { get; set; }
        public string U14_GlobalLock { get; set; }
        public string U14_SysRevID { get; set; }
        public string U14_SysRowID { get; set; }
        
        public bool UrgentOrder { get; set; }
        public string BumiAgDONum { get; set; }
        public bool SerialNum { get; set; }

        /*
        public string Company { get; set; }
        public Int32 PackNum { get; set; }
        public string ShipDate { get; set; }
        public string ShipViaCode { get; set; }
        public string ShipPerson { get; set; }
        public string EntryPerson { get; set; }
        public string ShipLog { get; set; }
        public string LabelComment { get; set; }
        public string ShipComment { get; set; }
        public bool Invoiced { get; set; }
        public string ShipToNum { get; set; }
        public bool ReadyToInvoice { get; set; }
        public Int32 CustNum { get; set; }
        public string Plant { get; set; }
        public string TrackingNumber { get; set; }
        public string LegalNumber { get; set; }
        public bool Voided { get; set; }
        public bool ExternalDeliveryNote { get; set; }
        public string ExternalID { get; set; }
        public bool ICReceived { get; set; }
        public string XRefPackNum { get; set; }
        public Int32 BTCustNum { get; set; }
        public Int32 BTConNum { get; set; }
        public string ShipStatus { get; set; }
        public string ShipGroup { get; set; }
        public string PkgCode { get; set; }
        public string PkgClass { get; set; }
        public decimal Weight { get; set; }
        public bool ResDelivery { get; set; }
        public bool SatDelivery { get; set; }
        public bool SatPickup { get; set; }
        public bool VerbalConf { get; set; }
        public bool Hazmat { get; set; }
        public bool DocOnly { get; set; }
        public string RefNotes { get; set; }
        public bool ApplyChrg { get; set; }
        public decimal ChrgAmount { get; set; }
        public bool COD { get; set; }
        public bool CODFreight { get; set; }
        public bool CODCheck { get; set; }
        public decimal CODAmount { get; set; }
        public string GroundType { get; set; }
        public bool NotifyFlag { get; set; }
        public string NotifyEMail { get; set; }
        public bool DeclaredIns { get; set; }
        public decimal DeclaredAmt { get; set; }
        public string MFTransNum { get; set; }
        public string MFCallTag { get; set; }
        public string MFPickupNum { get; set; }
        public decimal MFDiscFreight { get; set; }
        public string MFTemplate { get; set; }
        public bool MFUse3B { get; set; }
        public string MF3BAccount { get; set; }
        public decimal MFDimWeight { get; set; }
        public string MFZone { get; set; }
        public decimal MFFreightAmt { get; set; }
        public decimal MFOtherAmt { get; set; }
        public bool MFOversized { get; set; }
        public bool ServSatDelivery { get; set; }
        public bool ServSatPickup { get; set; }
        public bool ServSignature { get; set; }
        public bool ServAlert { get; set; }
        public bool ServPOD { get; set; }
        public bool ServAOD { get; set; }
        public bool ServHomeDel { get; set; }
        public string DeliveryType { get; set; }
        public string ServDeliveryDate { get; set; }
        public string ServPhone { get; set; }
        public string ServInstruct { get; set; }
        public bool ServRelease { get; set; }
        public string ServAuthNum { get; set; }
        public string ServRef1  { get; set; }
        public string ServRef2 { get; set; }
        public string ServRef3 { get; set; }
        public string ServRef4 { get; set; }
        public string ServRef5 { get; set; }
        public Int32 BOLNum { get; set; }
        public Int32 BOLLine { get; set; }
        public bool CommercialInvoice { get; set; }
        public bool ShipExprtDeclartn { get; set; }
        public bool CertOfOrigin { get; set; }
        public bool LetterOfInstr { get; set; }
        public bool HazardousShipment { get; set; }
        public bool IntrntlShip { get; set; }
        public string PayFlag { get; set; }
        public string PayAccount { get; set; }
        public string PayBTAddress1 { get; set; }
        public string PayBTAddress2 { get; set; }
        public string PayBTCity { get; set; }
        public string PayBTState { get; set; }
        public string PayBTZip { get; set; }
        public string PayBTCountry { get; set; }
        public string FFAddress1 { get; set; }
        public string FFAddress2 { get; set; }
        public string FFCity { get; set; }
        public string FFState { get; set; }
        public string FFZip { get; set; }
        public string FFCountry { get; set; }
        public string FFContact { get; set; }
        public string FFCompName { get; set; }
        public string FFPhoneNum { get; set; }
        public string ChangedBy { get; set; }
        public string ChangeDate { get; set; }
        public Int32 ChangeTime { get; set; }
        public string FFID { get; set; }
        public bool IndividualPackIDs { get; set; }
        public string FFAddress3 { get; set; }
        public Int32 DeliveryConf { get; set; }
        public bool AddlHdlgFlag { get; set; }
        public bool NonStdPkg { get; set; }
        public Int32 FFCountryNum { get; set; }
        public string PayBTAddress3 { get; set; }
        public Int32 PayBTCountryNum { get; set; }
        public string PayBTPhone { get; set; }
        public string WayBillNbr { get; set; }
        public string FreightedShipViaCode { get; set; }
        public bool UPSQuantumView { get; set; }
        public string UPSQVShipFromName { get; set; }
        public string UPSQVMemo { get; set; }
        public decimal PkgLength { get; set; }
        public decimal PkgWidth { get; set; }
        public decimal PkgHeight { get; set; }
        public bool EDIReady { get; set; }
        public bool PhantomPack { get; set; }
        public Int32 ReplicatedFrom { get; set; }
      public string ReplicatedStat { get; set; }
      public string PkgSizeUOM  { get; set; }
      public string WeightUOM { get; set; }
      public bool UseOTS { get; set; }
      public string TranDocTypeID { get; set; }
      public bool DocumentPrinted { get; set; }
      public Int32 OTSOrderNum { get; set; }
      public bool TaxCalculated { get; set; }
      public string TaxCalcDate { get; set; }
      public string CurrencyCode { get; set; }
      public decimal Rounding { get; set; }
      public decimal Rpt1Rounding { get; set; }
      public decimal Rpt2Rounding { get; set; }
      public decimal Rpt3Rounding { get; set; }
      public decimal DocRounding { get; set; }
      public decimal Rpt1TotalTax { get; set; }
      public decimal Rpt2TotalTax { get; set; }
      public decimal Rpt3TotalTax { get; set; }
      public decimal OrderAmt { get; set; }
      public decimal DocOrderAmt { get; set; }
      public decimal Rpt1OrderAmt { get; set; }
      public decimal Rpt2OrderAmt { get; set; }
      public decimal Rpt3OrderAmt { get; set; }
      public string TaxRegionCode { get; set; }
      public decimal TotalWHTax { get; set; }
      public decimal DocTotalWHTax { get; set; }
      public decimal Rpt1TotalWHTax { get; set; }
      public decimal Rpt2TotalWHTax { get; set; }
      public decimal Rpt3TotalWHTax { get; set; }
      public decimal TotalSATax { get; set; }
      public decimal DocTotalSATax { get; set; }
      public decimal Rpt1TotalSATax { get; set; }
      public decimal Rpt2TotalSATax { get; set; }
      public decimal Rpt3TotalSATax { get; set; }
      public decimal TotalTax { get; set; }
      public decimal DocTotalTax { get; set; }
      public decimal TotalDiscount { get; set; }
      public decimal Rpt1TotalDiscount { get; set; }
      public decimal Rpt2TotalDiscount { get; set; }
      public decimal Rpt3TotalDiscount { get; set; }
      public decimal DocTotalDiscount { get; set; }
      public Int32 ShipToCustNum { get; set; }
      public string DeviceUOM { get; set; }
      public string ManifestSizeUOM { get; set; }
      public string ManifestWtUOM { get; set; }
      public decimal ManifestWeight { get; set; }
      public decimal ManifestLength { get; set; }
      public decimal ManifestWidth { get; set; }
      public decimal ManifestHeight { get; set; }
      public string RateGrpCode { get; set; }
      public bool InPrice { get; set; }
      public bool PBHoldNoInv { get; set; }
      public Int32 Obs10_PkgNum { get; set; }
      public decimal ReconcileQty { get; set; }
      public string ScheduleNumber { get; set; }
      public Int32 CounterASN { get; set; }
      public string OurBank { get; set; }
      public bool ERSOrder { get; set; }
      public bool AutoPrintReady { get; set; }
      public bool ShipOvers { get; set; }
      public bool WIPackSlipCreated { get; set; }
      public string SysRevID { get; set; }
      public string SysRowID { get; set; }
      public string AGAuthorizationCode { get; set; }
      public string AGAuthorizationDate { get; set; }
      public string AGCarrierCUIT { get; set; }
      public bool AGCOTMark { get; set; }
      public string AGDocumentLetter { get; set; }
      public string AGInvoicingPoint { get; set; }
      public string AGLegalNumber { get; set; }
      public string AGPrintingControlType { get; set; }
      public string AGTrackLicense { get; set; }
      public string DispatchReason { get; set; }
      public string AGShippingWay { get; set; }
      public string OurSupplierCode { get; set; }
      public string ASNPrintedDate { get; set; }
      public string EDIShipToNum { get; set; }
      public string MXIncoterm { get; set; }
      public string CreatedOn { get; set; }
      public string DigitalSignature { get; set; }
      public string SignedOn { get; set; }
      public string SignedBy { get; set; }
      public string FirstPrintDate { get; set; }
      public Int32 DocCopyNum { get; set; }

        */


    }
}